modLoader = 'lowcodefml'
loaderVersion = '[53,)'
license = 'ARR'

[[mods]]
modId = 'health_enchant'
version = '2.0'
displayName = 'Health Enchantment'
description = 'New enchantment that, when applied to armor, allows to get more health!'
logoFile = 'pack.png'
authors = 'GRgabrix'
displayURL = 'https://modrinth.com/mod/health-enchant'
sourceURL = 'https://github.com/GRgabrix/Health-Enchantment'
