modLoader = 'lowcodefml'
loaderVersion = '[21.0, 21.2)'
license = 'ARR'

[[mods]]
modId = 'health_enchant'
version = '1.1'
displayName = 'Health Enchantment'
description = 'New enchantment that, when applied to armor, allows to get more health!'
logoFile = 'pack.png'
authors = 'GRgabrix'
displayURL = 'https://modrinth.com/mod/health-enchant'